default_job = "tic80"

# This section defines the command to run after a successful build.
[jobs.tic80]
command = [
    "sh", "-c", "cargo build --release --target=wasm32-unknown-unknown; tic80 --skip --fs . --cmd 'new wasm & import binary target/wasm32-unknown-unknown/release/ronin.wasm & import tiles res/tilesheet.png & import sprites res/spritesheet.png & run'"
]
on_change_strategy = "kill_then_restart"

# Optional: Configuration for the project watch behavior
[default.project]
# Exclude files/directories that change frequently but shouldn't trigger a build
# such as lock files or temporary directories.
exclude = [
    ".git",
    "target",
    "**/*.swp",
    "Cargo.lock",
]
